# Site settings
title: Comparing CVR and RSFA reliability
email: s.moia@bcbl.eu
description: Assessment of longitudinal cerebrovascular reactivity measurements based on breath-hold and resting state BOLD multi-echo fMRI
baseurl: "/cvr-meica-motion-removal" # the subpath of your site, e.g. /blog
url: "https://smoia.github.io" # the base hostname & protocol for your site

# Misc settings
featured-image-source:

# Build settings
markdown: kramdown
collections:
  - sections

# Social settings (Will appear in the footer)
500px_url:
facebook_url:
github_url: https://smoia.github.io
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/SteMoia

# Homepage tiles (The "in a nutshell")
tiles-source: sections # accepts "sections", "posts" or "pages"
tiles-count: 3

# Outreach Data
out_title: Assessment of longitudinal cerebrovascular reactivity measurements based on breath-hold and resting state BOLD multi-echo fMRI
out_authors: Stefano Moia, Rachael Stickland, Maite Termenon, Eneko Uruñuela, César Caballero-Gaudes, Molly Bright
take_home: CVR estimated from Breath-Hold fMRI is more reliable than CVR estimated from RSFA, but this effect shows substantial spatial variation.
downloadable:
  - {name: ISMRM2020, file: 3855_ISMRM_Moia.pdf, type: poster}